// #include <iostream>
// using namespace std ;

// int main(){
//     int i;
//     int answar = 0;
//     string sum =" ";

//     cout << "Enter your input" << endl;
//     cin >>i;
//     for (int i=0; i<i; i++){
//         string num ;
//         cout << "enter number => ";
//         cin >>num;
//         sum = sum+num;


//          answar =answar+stoi(num) 
//     }
//    cout << sum<<"="<<answar;
// }


#include <iostream>
using namespace std;
int main(){
     int i ;
     cout<<"Enter number => "<<endl;
     cin >>i;

     int arr[n] ={};
     for(int i=0;i<i;i++){
        cin >>arr[i];

     }
     int sum = 0;
     for(int i=0;i<i;i++){
        cout<<arr[i]
     }
     }
